export const uiEnglish: Record<string, string> = {
  'Neue / identische / gesperrte Quellfragen': 'New / identical / blocked source questions',
  'Neue Fragen werden in einem neuen privaten Katalog angelegt. Identische Quellfragen bleiben in ihren bisherigen Katalogen. Es wird nichts veröffentlicht. Originalpaket und neue Anzeigebilder belegen Speicherplatz.':
    'New questions are created in a new private catalog. Identical source questions remain in their existing catalogs. Nothing is published. The original package and new display images use storage space.',
  'Eigene Fragen als Paket exportieren': 'Export your questions as a package',
  'Der lokale ZIP-Download enthält nur ausgewählte Frageinhalte. Konten, Lernstände und Gruppencodes werden nicht exportiert. Es wird nichts veröffentlicht.':
    'The local ZIP contains only selected question content. Accounts, learning progress and group codes are excluded. Nothing is published.',
  'Gespeicherte Entwürfe haben Vorrang vor veröffentlichten Fassungen. Speichere Änderungen im Editor und aktualisiere anschließend die Auswahl.':
    'Saved drafts take precedence over published versions. Save editor changes, then refresh the selection.',
  'Auswahl aktualisieren': 'Refresh selection',
  'Fragen auswählen': 'Select questions',
  'Alle eigenen Fragen': 'All your questions',
  'Alle eigenen Fragen auswählen': 'Select all your questions',
  'Gefilterte Fragen auswählen': 'Select filtered questions',
  'Auswahl leeren': 'Clear selection',
  'Fragen ausgewählt (maximal 500)': 'questions selected (maximum 500)',
  Entwurf: 'Draft',
  'Gespeicherte Fassung': 'Saved version',
  Pakettitel: 'Package title',
  'Herausgeber / Attributionsname': 'Publisher / attribution name',
  'Diese Metadaten stehen im ZIP. Verwende keine E-Mail-Adresse oder andere vertrauliche Angaben als Attributionsnamen.':
    'These metadata are included in the ZIP. Do not use email addresses or confidential information as attribution names.',
  'Rechte eigener Originaltexte und Originalbilder': 'Rights for your original texts and images',
  'Die folgenden Angaben gelten ausschließlich für eigene Originalinhalte. Importierte Originalfragen behalten ihre tatsächlichen Einzellizenzen und Quellen. Bearbeitete Importfragen oder unvollständige Drittquellennachweise sperren den Export.':
    'These details apply only to your original content. Imported originals retain their individual licenses and sources. Edited imports or incomplete third-party evidence block export.',
  'Lizenz eigener Texte': 'License for your texts',
  'Rechteinhaber der Texte': 'Text rights holder',
  'Attribution der Texte': 'Text attribution',
  'Lizenz eigener Bilder': 'License for your images',
  'Rechteinhaber der Bilder': 'Image rights holder',
  'Attribution der Bilder': 'Image attribution',
  'Lizenztexte, Lizenzverweise und Nutzungsbedingungen':
    'License texts, references and terms of use',
  'LicenseRef-Private ist keine offene Lizenz. Der private Export verlangt keine Community-Freigabe. Eine andere Lizenz darf nur bewusst und mit den nötigen Rechten gewählt werden; die technische Prüfung bestätigt keine rechtliche Zulässigkeit.':
    'LicenseRef-Private is not an open license. Private export does not require community approval. Choose another license only deliberately and with the necessary rights; technical validation does not establish legal permission.',
  'Exportvorschau prüfen': 'Check export preview',
  Exportvorschau: 'Export preview',
  'Ich bestätige die Exportrechte. Die als eigene Originale ausgezeichneten Texte und Bilder stammen von mir und dürfen mit diesen Angaben exportiert werden.':
    'I confirm the export rights. Texts and images marked as my originals were created by me and may be exported with these details.',
  'LearnPip-Paket (.zip) herunterladen': 'Download LearnPip package (.zip)',
  'Auswahl konnte nicht geladen werden. Bitte Anmeldung prüfen.':
    'Selection could not be loaded. Please check your sign-in.',
  'Export geprüft. Bitte Inhalte, Lizenzen und Attribution vor dem Download kontrollieren.':
    'Export validated. Review content, licenses and attribution before downloading.',
  'ZIP heruntergeladen. Auf der anderen Instanz unter Fragen importieren oder Kataloge und Inhalte auswählen.':
    'ZIP downloaded. On the other instance, choose Import questions or Catalogs and content.',
  'Export fehlgeschlagen. Bitte Auswahl und Rechteangaben prüfen.':
    'Export failed. Check the selection and rights information.',
  'Fragen auswählen und exportieren': 'Select and export questions',
  'Fragen importieren': 'Import questions',
  'Ablauf in Tagen': 'Expires in days',
  Ablehnen: 'Reject',
  'Aktivität aktualisieren': 'Refresh activity',
  Aktualisieren: 'Refresh',
  'Aktuelle Fassungen freigeben': 'Share current versions',
  'Alle Entwürfe': 'All drafts',
  'Alle Fragen des gewählten Profils in Etappen ohne Zeitlimit. Die Fehleranalyse erscheint nach der letzten Etappe.':
    'All questions in the selected profile, in stages without a time limit. Error analysis appears after the final stage.',
  'Alle Fragen richtig beantwortet.': 'All questions answered correctly.',
  'Als privaten Entwurf speichern': 'Save as private draft',
  Alterserklärung: 'Age declaration',
  'An gewählten Anbieter senden': 'Send to selected provider',
  Anlegen: 'Create',
  'Antwort ergänzen': 'Add answer',
  'Antwort hinzufügen': 'Add answer',
  Antworten: 'Answers',
  'Antworten und Korrektheit': 'Answers and correctness',
  'Antworten · richtige Lösung selbst festlegen': 'Answers · choose the correct one yourself',
  Antworttext: 'Answer text',
  Anzeigen: 'Show',
  Auswahlart: 'Answer type',
  'Auswertung je Fachteil': 'Results by subject section',
  'Bearbeitbare Variante zum Lerninhalt anlegen':
    'Create editable variant for this learning content',
  Begründung: 'Reason',
  'Begründung/Notiz': 'Reason / note',
  Beherrschungsgrad: 'Mastery level',
  Beitreten: 'Join',
  'Bereits bestandene Fachbereiche (Selbstauskunft)':
    'Subject areas already passed (self reported)',
  'Bereitschaft einschätzen': 'Estimate readiness',
  Beschreibung: 'Description',
  Betriebsart: 'Mode',
  'Bewertung entfernen': 'Remove rating',
  'Bild (JPEG oder PNG, maximal 5 MiB)': 'Image (JPEG or PNG, up to 5 MiB)',
  'Bild aus Frage entfernen': 'Remove image from question',
  'Bild entfernen': 'Remove image',
  'Bild löschen': 'Delete image',
  'Bildbereich in Prozent zuschneiden': 'Crop image area in percent',
  Bildbeschreibung: 'Image description',
  'Bildbeschreibung für deinen Entwurf': 'Image description for your draft',
  'Bilddatei (optional)': 'Image file (optional)',
  'Bildrechte geprüft': 'Image rights checked',
  'Bis zur Löschung kannst du dich mit deinem Wiederherstellungsgeheimnis, deiner verknüpften E-Mail oder OIDC erneut anmelden und das Konto reaktivieren.':
    'Until deletion, you can sign in with your recovery secret, linked email or OIDC to reactivate the account.',
  'Bitte auswählen': 'Please select',
  'Bitte bewusst auswählen': 'Choose deliberately',
  'Bitte wählen': 'Please choose',
  Breite: 'Width',
  'Code erstellen': 'Create code',
  'Code nur jetzt kopieren:': 'Copy the code now:',
  'Code widerrufen': 'Revoke code',
  'Datenweg:': 'Data transfer:',
  'Dein Konto': 'Your account',
  'Dein Lernweg': 'Your learning progress',
  'Deine Themen': 'Your topics',
  'Details prüfen': 'Review details',
  'Die Zeit läuft je Fachteil ab Start auch nach Schließen der Seite weiter. Offene Läufe können fortgesetzt werden.':
    "Each section's timer continues after you close the page. You can resume unfinished attempts.",
  'Diese Fassung zur Moderation einreichen': 'Submit this version for moderation',
  'Dubletten geprüft': 'Duplicates checked',
  'Eigene Fragen erstellen und lernen funktioniert auch ohne KI.':
    'You can create questions and learn without AI.',
  'Eigenen API-Schlüssel verwalten': 'Manage your own API key',
  'Eigener Katalog': 'My catalog',
  'Ein belastbares Bereitschaftsfenster lässt sich noch nicht ableiten.':
    'A reliable readiness window cannot be estimated yet.',
  'Eine richtige Antwort': 'One correct answer',
  Einladungscode: 'Invitation code',
  'Empfänger einer späteren KI-Anfrage:': 'Recipient of a later AI request:',
  'Empfänger:': 'Recipient:',
  Entfernen: 'Remove',
  'Erfolgreiche angemeldete API-Aufrufe halten dein Konto aktiv. Nach 60, 76 und 87 Tagen ohne Aktivität erhältst du eine E-Mail-Erinnerung, wenn eine Adresse verknüpft und der Mailversand eingerichtet ist. Nach 90 Tagen wird das Konto deaktiviert. Weitere 90 Tage später wird es gelöscht.':
    'Authenticated API activity keeps your account active. After 60, 76 and 87 inactive days, you receive an email reminder if email is linked and delivery is configured. The account is deactivated after 90 days and deleted 90 days later.',
  'Erkannter Text': 'Recognized text',
  'Erkennung prüfen und korrigieren': 'Review and correct recognition',
  Erklärung: 'Explanation',
  'Errechnete Lösung (ungeprüft)': 'Calculated solution (unverified)',
  'Erstelle Fragen mit Text oder Foto, speichere sie privat und veröffentliche eine Fassung erst, wenn du bereit bist.':
    'Create questions from text or photos, save them privately and publish a version when you are ready.',
  'Erstelle und veröffentliche eine Frage, um deinen Lernweg zu beginnen.':
    'Create and publish a question to start tracking your progress.',
  'Erstelle zuerst Lerninhalte, um einen Plan zu schätzen.':
    'Create learning content before estimating a plan.',
  'Erster Hinweis ohne Lösung': 'First hint without the answer',
  'Etappe abgeben': 'Submit stage',
  Fach: 'Subject',
  'Fachteil abgeben': 'Submit subject section',
  Fehleranalyse: 'Error analysis',
  'Formale Zulassung': 'Formal eligibility',
  Formel: 'Formula',
  'Foto auswählen (JPEG oder PNG, höchstens 5 MiB)': 'Select photo (JPEG or PNG, up to 5 MiB)',
  'Foto in privaten Aufgabenentwurf übernehmen': 'Create private question draft from photo',
  'Foto mit gewähltem Anbieter analysieren': 'Analyze photo with selected provider',
  'Foto oder Bilddatei zur Frage': 'Photo or image file for the question',
  'Fotos und Zeichnungen bleiben in deinem Konto. Melde dich an, bevor du ein Bild hochlädst.':
    'Photos and drawings stay in your account. Sign in before uploading an image.',
  Frage: 'Question',
  'Frage auswählen': 'Select question',
  'Frage löschen': 'Delete question',
  Fragen: 'Questions',
  'Fragen besprechen': 'Discuss questions',
  'Fragen pro Etappe': 'Questions per stage',
  'Fragen sammeln': 'Collect questions',
  'Freigabe aufheben': 'Revoke sharing',
  'Freigabe oder Einreichung zurückziehen': 'Withdraw sharing or submission',
  Freigeben: 'Approve',
  'Freigegebene Kataloge': 'Shared catalogs',
  'Für diese Profilfassung sind keine geprüften Termine hinterlegt.':
    'No verified dates are stored for this profile version.',
  'Für diese ältere Profilfassung ist kein geprüfter Regelstand hinterlegt.':
    'No verified rules are stored for this older profile version.',
  Gemischt: 'Mixed',
  'Geschlossene Lerngruppen': 'Private study groups',
  'Gewünschter Beherrschungsgrad in Prozent': 'Desired mastery level in percent',
  Grund: 'Reason',
  'Gruppe erstellen': 'Create group',
  Gruppenname: 'Group name',
  Handlungsoptionen: 'Suggested actions',
  Herkunft: 'Source',
  'Hier gibt es keine tägliche Serie, die nach einer Pause verloren geht. Deine Ergebnisse bleiben erhalten.':
    'There is no daily streak to lose after a break. Your results remain available.',
  Hilfreich: 'Helpful',
  Höhe: 'Height',
  'Ich besitze die nötigen Bildrechte und habe persönliche Daten geprüft. Schulbuchfotos ohne Rechte darf ich nicht einreichen.':
    'I have the necessary image rights and have checked for personal data. I must not submit textbook photos without permission.',
  'Ich besitze die nötigen Rechte an Text und Antworten und stimme der gewählten öffentlichen Lizenz zu.':
    'I have the necessary rights to the text and answers and agree to the selected public license.',
  'Ich darf das Foto verarbeiten und bestätige die Übermittlung des Zuschnitts und der optionalen Musterlösung genau an den angezeigten Empfänger.':
    'I have the right to process this photo and approve sending the crop and optional reference solution to the shown recipient.',
  'Ich habe Bild, Frage, Antworten und Lösung geprüft oder offene Unsicherheiten erkannt. Nur einen privaten Entwurf speichern.':
    'I reviewed the image, question, answers and solution or identified uncertainties. Save a private draft only.',
  'Ich habe Empfänger und Datenübermittlung gelesen und möchte genau diesen Text senden.':
    'I have read the recipient and transfer details and want to send this exact text.',
  'Ich möchte nur diesen Zuschnitt privat bei LearnPip hochladen.':
    'I want to upload only this crop privately to LearnPip.',
  'Inhaltlich falsch': 'Factually incorrect',
  Inhaltslizenz: 'Content license',
  'JSON-Import mit Quelle, Lizenz, Urheberangabe, Fassungsdatum und bestätigten Rechten.':
    'JSON import with source, license, author credit, version date and confirmed rights.',
  'Jede Fassung bleibt bis zur vollständigen Prüfung privat. Einreichungen Minderjähriger können ohne gesondertes Verfahren nicht freigegeben werden.':
    'Each version remains private until fully reviewed. Submissions by minors cannot be approved without a separate process.',
  'Jeder kleine Schritt zählt. Eine Pause nimmt dir keinen Fortschritt weg.':
    'Every small step counts. A break does not erase your progress.',
  'Jeder verlangte Fachteil wird getrennt bewertet. Selbst gemeldete bestandene Teile ersetzen keinen amtlichen Nachweis.':
    'Each required section is assessed separately. Self reported passes do not replace official evidence.',
  Katalog: 'Catalog',
  'Katalog löschen': 'Delete catalog',
  'Katalogfassung importieren': 'Import catalog version',
  'Katalogimport (JSON)': 'Catalog import (JSON)',
  'Katalogname ändern': 'Rename catalog',
  Katalogquellen: 'Catalog sources',
  Kommentar: 'Comment',
  'Kommentar entfernen': 'Remove comment',
  Kommentare: 'Comments',
  Kommentieren: 'Post comment',
  'Korrektheit geprüft': 'Correctness checked',
  'Korrigierte Lösung unabhängig prüfen': 'Independently check corrected solution',
  'Korrigierter Fragetext': 'Corrected question text',
  'Kurze Einheiten in den letzten vier Wochen': 'Short sessions in the last four weeks',
  'LearnPip meldet niemanden automatisch zur Prüfung an.':
    'LearnPip does not register anyone for an exam automatically.',
  Lernbereitschaft: 'Learning readiness',
  'Lerninhalte sicher': 'Mastered content',
  'Lerntage insgesamt': 'Total learning days',
  Lernzeit: 'Study time',
  'Lernzeit pro Tag in Minuten': 'Study time per day in minutes',
  'Letzte Aktivität vor diesem Seitenaufruf:': 'Last activity before this page view:',
  Links: 'Left',
  Lizenz: 'License',
  'Lösungsweg (eine Zeile je Schritt)': 'Solution steps (one per line)',
  'Lösungsweg und Erklärung': 'Solution steps and explanation',
  'Mehrere richtige Antworten': 'Multiple correct answers',
  'Mein Lernstoff': 'My learning material',
  'Meldung senden': 'Send report',
  'Meldungen prüfen': 'Review reports',
  'Meldungen schließen': 'Close reports',
  'Minderjährig (gesonderte Prüfung ohne Freigabe)': 'Minor (separate review without approval)',
  Mitglieder: 'Members',
  'Mitglieder und Kataloge anzeigen': 'Show members and catalogs',
  Mitmachpunkte: 'Participation points',
  'Musterlösung aus der Vorlage': 'Reference solution from the source',
  'Musterlösung aus der Vorlage (falls lesbar, optional)':
    'Reference solution from the source (if legible, optional)',
  'Neue Frage': 'New question',
  'Neue private Version erstellen': 'Create new private version',
  'Neuer Schlüssel': 'New key',
  'Nicht hilfreich': 'Not helpful',
  Nutzungen: 'Uses',
  'Nächster Schritt ohne Lösung': 'Next step without the answer',
  Oben: 'Top',
  'Offiziellen Katalog und Profilfassungen verwalten':
    'Manage official catalog and profile versions',
  'Ohne KI selbst erfassen': 'Enter manually without AI',
  'Ohne Kat