export const uiEnglish: Record<string, string> = {
  'Ablauf in Tagen': 'Expires in days',
  Ablehnen: 'Reject',
  'Aktivität aktualisieren': 'Refresh activity',
  Aktualisieren: 'Refresh',
  'Aktuelle Fassungen freigeben': 'Share current versions',
  'Alle Entwürfe': 'All drafts',
  'Alle Fragen des gewählten Profils in Etappen ohne Zeitlimit. Die Fehleranalyse erscheint nach der letzten Etappe.':
    'All questions in the selected profile, in stages without a time limit. Error analysis appears after the final stage.',
  'Alle Fragen richtig beantwortet.': 'All questions answered correctly.',
  'Als privaten Entwurf speichern': 'Save as private draft',
  Alterserklärung: 'Age declaration',
  'An gewählten Anbieter senden': 'Send to selected provider',
  Anlegen: 'Create',
  'Antwort ergänzen': 'Add answer',
  'Antwort hinzufügen': 'Add answer',
  Antworten: 'Answers',
  'Antworten und Korrektheit': 'Answers and correctness',
  'Antworten · richtige Lösung selbst festlegen': 'Answers · choose the correct one yourself',
  Antworttext: 'Answer text',
  Anzeigen: 'Show',
  Auswahlart: 'Answer type',
  'Auswertung je Fachteil': 'Results by subject section',
  'Bearbeitbare Variante zum Lerninhalt anlegen':
    'Create editable variant for this learning content',
  Begründung: 'Reason',
  'Begründung/Notiz': 'Reason / note',
  Beherrschungsgrad: 'Mastery level',
  Beitreten: 'Join',
  'Bereits bestandene Fachbereiche (Selbstauskunft)':
    'Subject areas already passed (self reported)',
  'Bereitschaft einschätzen': 'Estimate readiness',
  Beschreibung: 'Description',
  Betriebsart: 'Mode',
  'Bewertung entfernen': 'Remove rating',
  'Bild (JPEG oder PNG, maximal 5 MiB)': 'Image (JPEG or PNG, up to 5 MiB)',
  'Bild aus Frage entfernen': 'Remove image from question',
  'Bild entfernen': 'Remove image',
  'Bild löschen': 'Delete image',
  'Bildbereich in Prozent zuschneiden': 'Crop image area in percent',
  Bildbeschreibung: 'Image description',
  'Bildbeschreibung für deinen Entwurf': 'Image description for your draft',
  'Bilddatei (optional)': 'Image file (optional)',
  'Bildrechte geprüft': 'Image rights checked',
  'Bis zur Löschung kannst du dich mit deinem Wiederherstellungsgeheimnis, deiner verknüpften E-Mail oder OIDC erneut anmelden und das Konto reaktivieren.':
    'Until deletion, you can sign in with your recovery secret, linked email or OIDC to reactivate the account.',
  'Bitte auswählen': 'Please select',
  'Bitte bewusst auswählen': 'Choose deliberately',
  'Bitte wählen': 'Please choose',
  Breite: 'Width',
  'Code erstellen': 'Create code',
  'Code nur jetzt kopieren:': 'Copy the code now:',
  'Code widerrufen': 'Revoke code',
  'Datenweg:': 'Data transfer:',
  'Dein Konto': 'Your account',
  'Dein Lernweg': 'Your learning progress',
  'Deine Themen': 'Your topics',
  'Details prüfen': 'Review details',
  'Die Zeit läuft je Fachteil ab Start auch nach Schließen der Seite weiter. Offene Läufe können fortgesetzt werden.':
    "Each section's timer continues after you close the page. You can resume unfinished attempts.",
  'Diese Fassung zur Moderation einreichen': 'Submit this version for moderation',
  'Dubletten geprüft': 'Duplicates checked',
  'Eigene Fragen erstellen und lernen funktioniert auch ohne KI.':
    'You can create questions and learn without AI.',
  'Eigenen API-Schlüssel verwalten': 'Manage your own API key',
  'Eigener Katalog': 'My catalog',
  'Ein belastbares Bereitschaftsfenster lässt sich noch nicht ableiten.':
    'A reliable readiness window cannot be estimated yet.',
  'Eine richtige Antwort': 'One correct answer',
  Einladungscode: 'Invitation code',
  'Empfänger einer späteren KI-Anfrage:': 'Recipient of a later AI request:',
  'Empfänger:': 'Recipient:',
  Entfernen: 'Remove',
  'Erfolgreiche angemeldete API-Aufrufe halten dein Konto aktiv. Nach 60, 76 und 87 Tagen ohne Aktivität erhältst du eine E-Mail-Erinnerung, wenn eine Adresse verknüpft und der Mailversand eingerichtet ist. Nach 90 Tagen wird das Konto deaktiviert. Weitere 90 Tage später wird es gelöscht.':
    'Authenticated API activity keeps your account active. After 60, 76 and 87 inactive days, you receive an email reminder if email is linked and delivery is configured. The account is deactivated after 90 days and deleted 90 days later.',
  'Erkannter Text': 'Recognized text',
  'Erkennung prüfen und korrigieren': 'Review and correct recognition',
  Erklärung: 'Explanation',
  'Errechnete Lösung (ungeprüft)': 'Calculated solution (unverified)',
  'Erstelle Fragen mit Text oder Foto, speichere sie privat und veröffentliche eine Fassung erst, wenn du bereit bist.':
    'Create questions from text or photos, save them privately and publish a version when you are ready.',
  'Erstelle und veröffentliche eine Frage, um deinen Lernweg zu beginnen.':
    'Create and publish a question to start tracking your progress.',
  'Erstelle zuerst Lerninhalte, um einen Plan zu schätzen.':
    'Create learning content before estimating a plan.',
  'Erster Hinweis ohne Lösung': 'First hint without the answer',
  'Etappe abgeben': 'Submit stage',
  Fach: 'Subject',
  'Fachteil abgeben': 'Submit subject section',
  Fehleranalyse: 'Error analysis',
  'Formale Zulassung': 'Formal eligibility',
  Formel: 'Formula',
  'Foto auswählen (JPEG oder PNG, höchstens 5 MiB)': 'Select photo (JPEG or PNG, up to 5 MiB)',
  'Foto in privaten Aufgabenentwurf übernehmen': 'Create private question draft from photo',
  'Foto mit gewähltem Anbieter analysieren': 'Analyze photo with selected provider',
  'Foto oder Bilddatei zur Frage': 'Photo or image file for the question',
  'Fotos und Zeichnungen bleiben in deinem Konto. Melde dich an, bevor du ein Bild hochlädst.':
    'Photos and drawings stay in your account. Sign in before uploading an image.',
  Frage: 'Question',
  'Frage auswählen': 'Select question',
  'Frage löschen': 'Delete question',
  Fragen: 'Questions',
  'Fragen besprechen': 'Discuss questions',
  'Fragen pro Etappe': 'Questions per stage',
  'Fragen sammeln': 'Collect questions',
  'Freigabe aufheben': 'Revoke sharing',
  'Freigabe oder Einreichung zurückziehen': 'Withdraw sharing or submission',
  Freigeben: 'Approve',
  'Freigegebene Kataloge': 'Shared catalogs',
  'Für diese Profilfassung sind keine geprüften Termine hinterlegt.':
    'No verified dates are stored for this profile version.',
  'Für diese ältere Profilfassung ist kein geprüfter Regelstand hinterlegt.':
    'No verified rules are stored for this older profile version.',
  Gemischt: 'Mixed',
  'Geschlossene Lerngruppen': 'Private study groups',
  'Gewünschter Beherrschungsgrad in Prozent': 'Desired mastery level in percent',
  Grund: 'Reason',
  'Gruppe erstellen': 'Create group',
  Gruppenname: 'Group name',
  Handlungsoptionen: 'Suggested actions',
  Herkunft: 'Source',
  'Hier gibt es keine tägliche Serie, die nach einer Pause verloren geht. Deine Ergebnisse bleiben erhalten.':
    'There is no daily streak to lose after a break. Your results remain available.',
  Hilfreich: 'Helpful',
  Höhe: 'Height',
  'Ich besitze die nötigen Bildrechte und habe persönliche Daten geprüft. Schulbuchfotos ohne Rechte darf ich nicht einreichen.':
    'I have the necessary image rights and have checked for personal data. I must not submit textbook photos without permission.',
  'Ich besitze die nötigen Rechte an Text und Antworten und stimme der gewählten öffentlichen Lizenz zu.':
    'I have the necessary rights to the text and answers and agree to the selected public license.',
  'Ich darf das Foto verarbeiten und bestätige die Übermittlung des Zuschnitts und der optionalen Musterlösung genau an den angezeigten Empfänger.':
    'I have the right to process this photo and approve sending the crop and optional reference solution to the shown recipient.',
  'Ich habe Bild, Frage, Antworten und Lösung geprüft oder offene Unsicherheiten erkannt. Nur einen privaten Entwurf speichern.':
    'I reviewed the image, question, answers and solution or identified uncertainties. Save a private draft only.',
  'Ich habe Empfänger und Datenübermittlung gelesen und möchte genau diesen Text senden.':
    'I have read the recipient and transfer details and want to send this exact text.',
  'Ich möchte nur diesen Zuschnitt privat bei LearnPip hochladen.':
    'I want to upload only this crop privately to LearnPip.',
  'Inhaltlich falsch': 'Factually incorrect',
  Inhaltslizenz: 'Content license',
  'JSON-Import mit Quelle, Lizenz, Urheberangabe, Fassungsdatum und bestätigten Rechten.':
    'JSON import with source, license, author credit, version date and confirmed rights.',
  'Jede Fassung bleibt bis zur vollständigen Prüfung privat. Einreichungen Minderjähriger können ohne gesondertes Verfahren nicht freigegeben werden.':
    'Each version remains private until fully reviewed. Submissions by minors cannot be approved without a separate process.',
  'Jeder kleine Schritt zählt. Eine Pause nimmt dir keinen Fortschritt weg.':
    'Every small step counts. A break does not erase your progress.',
  'Jeder verlangte Fachteil wird getrennt bewertet. Selbst gemeldete bestandene Teile ersetzen keinen amtlichen Nachweis.':
    'Each required section is assessed separately. Self reported passes do not replace official evidence.',
  Katalog: 'Catalog',
  'Katalog löschen': 'Delete catalog',
  'Katalogfassung importieren': 'Import catalog version',
  'Katalogimport (JSON)': 'Catalog import (JSON)',
  'Katalogname ändern': 'Rename catalog',
  Katalogquellen: 'Catalog sources',
  Kommentar: 'Comment',
  'Kommentar entfernen': 'Remove comment',
  Kommentare: 'Comments',
  Kommentieren: 'Post comment',
  'Korrektheit geprüft': 'Correctness checked',
  'Korrigierte Lösung unabhängig prüfen': 'Independently check corrected solution',
  'Korrigierter Fragetext': 'Corrected question text',
  'Kurze Einheiten in den letzten vier Wochen': 'Short sessions in the last four weeks',
  'LearnPip meldet niemanden automatisch zur Prüfung an.':
    'LearnPip does not register anyone for an exam automatically.',
  Lernbereitschaft: 'Learning readiness',
  'Lerninhalte sicher': 'Mastered content',
  'Lerntage insgesamt': 'Total learning days',
  Lernzeit: 'Study time',
  'Lernzeit pro Tag in Minuten': 'Study time per day in minutes',
  'Letzte Aktivität vor diesem Seitenaufruf:': 'Last activity before this page view:',
  Links: 'Left',
  Lizenz: 'License',
  'Lösungsweg (eine Zeile je Schritt)': 'Solution steps (one per line)',
  'Lösungsweg und Erklärung': 'Solution steps and explanation',
  'Mehrere richtige Antworten': 'Multiple correct answers',
  'Mein Lernstoff': 'My learning material',
  'Meldung senden': 'Send report',
  'Meldungen prüfen': 'Review reports',
  'Meldungen schließen': 'Close reports',
  'Minderjährig (gesonderte Prüfung ohne Freigabe)': 'Minor (separate review without approval)',
  Mitglieder: 'Members',
  'Mitglieder und Kataloge anzeigen': 'Show members and catalogs',
  Mitmachpunkte: 'Participation points',
  'Musterlösung aus der Vorlage': 'Reference solution from the source',
  'Musterlösung aus der Vorlage (falls lesbar, optional)':
    'Reference solution from the source (if legible, optional)',
  'Neue Frage': 'New question',
  'Neue private Version erstellen': 'Create new private version',
  'Neuer Schlüssel': 'New key',
  'Nicht hilfreich': 'Not helpful',
  Nutzungen: 'Uses',
  'Nächster Schritt ohne Lösung': 'Next step without the answer',
  Oben: 'Top',
  'Offiziellen Katalog und Profilfassungen verwalten':
    'Manage official catalog and profile versions',
  'Ohne KI selbst erfassen': 'Enter manually without AI',
  'Ohne Katalog': 'No catalog',
  'Optionale KI-Unterstützung': 'Optional AI assistance',
  'Optionaler Prüfungstermin': 'Optional exam date',
  Originalfragen: 'Original questions',
  'Pausentage (Datum, kommagetrennt)': 'Break days (comma separated dates)',
  'Persönliche Daten': 'Personal data',
  'Persönliche Daten geprüft': 'Personal data checked',
  'Planungshorizont in Tagen': 'Planning horizon in days',
  'Posteingang aktualisieren': 'Refresh inbox',
  Powertest: 'Power test',
  'Powertest fortsetzen': 'Resume power test',
  'Powertest starten': 'Start power test',
  'Privat speichern': 'Save privately',
  'Private Bilder': 'Private images',
  'Private Kataloge': 'Private catalogs',
  'Private Vorschau prüfen': 'Review private preview',
  'Privater Entwurf gespeichert. Er ist oben im Frageneditor geöffnet; Veröffentlichung und öffentliche Einreichung sind eigene Schritte.':
    'Private draft saved and opened in the question editor above. Publishing and public submission are separate steps.',
  'Privates Bild verwerfen': 'Discard private image',
  'Problem melden': 'Report problem',
  Profilfassung: 'Profile version',
  'Profilfassung (JSON)': 'Profile version (JSON)',
  'Profilfassung speichern': 'Save profile version',
  Prüfungssimulation: 'Exam simulation',
  'Prüfungsziel planen': 'Plan an exam goal',
  'Punkte gibt es für bewusstes Üben und Erklärungen, begrenzt pro Inhalt und Tag. Die Antwortgeschwindigkeit zählt nicht.':
    'Points reward deliberate practice and reading explanations, with limits per content and day. Answer speed does not count.',
  Quelle: 'Source',
  Rechte: 'Rights',
  Regelquelle: 'Rules source',
  Richtig: 'Correct',
  Schließen: 'Close',
  'Schlüssel löschen': 'Delete key',
  'Schlüssel speichern/ersetzen': 'Save or replace key',
  'Schultage (halbe verfügbare Lernzeit)': 'School days (half the available study time)',
  'Schwierigkeiten überwunden': 'Difficulties overcome',
  Schätzen: 'Estimate',
  'Simulation fortsetzen': 'Resume simulation',
  'Simulation starten': 'Start simulation',
  Sonstiges: 'Other',
  Sprache: 'Language',
  Stoffumfang: 'Material volume',
  'Tageslimit in Minuten': 'Daily limit in minutes',
  'Teile einen eigenen Katalog mit deiner Gruppe. Ein Einladungscode dient nur zum Beitritt.':
    'Share your own catalog with your group. An invitation code only grants membership.',
  Terminquelle: 'Date source',
  'Text für den gewählten Anbieter': 'Text for the selected provider',
  Thema: 'Topic',
  Umbenennen: 'Rename',
  'Ungeprüfter Vorschlag. Unleserliche Zeichen, Formeln und Zeichnungen im Foto vergleichen.':
    'Unverified suggestion. Compare illegible characters, formulas and drawings with the photo.',
  Unklar: 'Unclear',
  Urheberangabe: 'Author credit',
  Varianten: 'Variants',
  'Version zurückziehen': 'Withdraw version',
  Volljährig: 'Adult',
  'Von mir als richtig geprüft': 'I checked this answer as correct',
  'Vorschau der einzureichenden Fassung': 'Preview of the version to submit',
  'Weitere Aufgabe erfassen': 'Add another question',
  'Wähle zwei Größen aus. Die dritte wird grob geschätzt; es gibt keine Erfolgsgarantie.':
    'Choose two values. The third is estimated roughly; there is no guarantee of success.',
  'Zeichnung/Bildbeschreibung': 'Drawing / image description',
  'Zu schätzende Größe': 'Value to estimate',
  'Zugeschnittenes Bild privat gespeichert.': 'Cropped image saved privately.',
  'Zuschnitt anzeigen': 'Preview crop',
  'Zuschnitt privat hochladen': 'Upload crop privately',
  'Zuschnitt und Vorschau entstehen zuerst auf deinem Gerät. Das zugeschnittene Foto wird nur nach deiner Freigabe in deinem privaten Konto gespeichert. Eine KI-Auswertung ist optional.':
    'Crop and preview are created on your device. The cropped photo is stored in your private account only after you approve it. AI analysis is optional.',
  'Öffentliche Einreichung vorbereiten und Vorschau anzeigen':
    'Prepare public submission and show preview',
  'Öffentliche Einreichungen prüfen': 'Review public submissions',
  'Überarbeitung anfordern': 'Request changes',
  'Fragenpaket importieren': 'Import question package',
  'Wähle eine lokale LearnPip-ZIP-Datei. Der Import bleibt privat und benötigt keinen externen Dienst.':
    'Choose a local LearnPip ZIP file. The import remains private and needs no external service.',
  'LearnPip-Paket (.zip, maximal 25 MiB)': 'LearnPip package (.zip, maximum 25 MiB)',
  'Importvorschau prüfen': 'Review import preview',
  Paketversion: 'Package version',
  Formatversion: 'Format version',
  Quellenstand: 'Source revision',
  'Archivgröße / entpackte Originaldateien': 'Archive size / unpacked original files',
  Inhalt: 'Contents',
  Medien: 'Media',
  Themen: 'Topics',
  'Lizenzen, Quellen und Attribution prüfen': 'Review licenses, sources and attribution',
  'Dieses Paket wurde geändert. Der Import ist gesperrt, damit vorhandene Fragen und Lernstände erhalten bleiben. Kontrollierte Paketupdates sind noch nicht verfügbar.':
    'This package has changed. Import is blocked to preserve existing questions and progress. Controlled package updates are not yet available.',
  'Dieses Paket wurde bereits importiert. Es werden keine Duplikate angelegt; eigene Änderungen bleiben erhalten.':
    'This package has already been imported. No duplicates will be created; your changes are preserved.',
  'Alle Fragen werden in einem neuen privaten Katalog angelegt. Es wird nichts veröffentlicht. Originalpaket und Anzeigebilder belegen Speicherplatz; Bilder werden für die Anzeige bereinigt.':
    'All questions will be added to a new private catalog. Nothing will be published. The original package and display images use storage; images are sanitized for display.',
  'Ich habe die Lizenzangaben geprüft und darf diese Inhalte privat nutzen.':
    'I have reviewed the licenses and may use these contents privately.',
  'Import bestätigen': 'Confirm import',
  'Importierte Fragen anzeigen': 'Show imported questions',
  'Importierte Originalpakete': 'Imported original packages',
  'Der Download enthält das unveränderte Originalpaket mit sämtlichen Lizenz- und Quellenangaben. Spätere Änderungen in LearnPip sind darin nicht enthalten.':
    'The download contains the unchanged original package with all license and source information. Later changes in LearnPip are not included.',
  'Originalpaket herunterladen': 'Download original package',
  'Bitte eine ZIP-Datei von maximal 25 MiB auswählen.':
    'Please choose a ZIP file of no more than 25 MiB.',
  'Paket geprüft. Bitte die Vorschau und Lizenzangaben lesen.':
    'Package checked. Please review the preview and licenses.',
  'Fragenpaket privat importiert. Es wurde nichts veröffentlicht.':
    'Question package imported privately. Nothing was published.',
  'Paket konnte nicht verarbeitet werden. Bitte Anmeldung und Datei prüfen.':
    'The package could not be processed. Please check your session and file.',
  'Paket konnte nicht verarbeitet werden.': 'The package could not be processed.',
  'Paket wird verarbeitet …': 'Processing package …',
};
