// <auto-generated />
using System;
using LearnPip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnPip.Data.Migrations
{
    [DbContext(typeof(LearnPipDbContext))]
    partial class LearnPipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnPip.Data.Domain.UserAiCredential", b =>
                {
                    b.Property<Guid>("AccountId").HasColumnType("uuid");
                    b.Property<string>("Ciphertext").IsRequired().HasColumnType("text");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("AccountId");
                    b.ToTable("UserAiCredentials");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AiDailyUsage", b =>
                {
                    b.Property<Guid>("AccountId").HasColumnType("uuid");
                    b.Property<DateOnly>("Day").HasColumnType("date");
                    b.Property<string>("Mode").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<int>("UsedRequests").HasColumnType("integer");
                    b.HasKey("AccountId", "Day", "Mode");
                    b.ToTable("AiDailyUsages");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AdministrationAuditEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<Guid?>("ActorAccountId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("NewValue").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("PreviousValue").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("Target").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.HasKey("Id");
                    b.HasIndex("ActorAccountId");
                    b.HasIndex("CreatedAtUtc");
                    b.ToTable("AdministrationAuditEvents");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Key").HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Value").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.HasKey("Key");
                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("La…11497 tokens truncated…eOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Details").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<Guid>("QuestionTranslationId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("AccountId");
                    b.HasIndex("QuestionTranslationId", "CreatedAtUtc");
                    b.ToTable("TranslationReports");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<string>("AuthorAttribution").IsRequired().HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SelectionMode").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<string>("Visibility").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)")
                        .HasDefaultValue("private");
                    b.Property<string>("Subject").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Topic").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Language").IsRequired().HasMaxLength(35).HasColumnType("character varying(35)");
                    b.Property<string>("Source").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("License").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<DateTimeOffset>("PublishedAtUtc").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("QuestionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("QuestionVersions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Code")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttemptSelection", b =>
                {
                    b.Property<Guid>("StudyAttemptId").HasColumnType("uuid");
                    b.Property<Guid>("AnswerOptionId").HasColumnType("uuid");
                    b.HasKey("StudyAttemptId", "AnswerOptionId");
                    b.HasIndex("AnswerOptionId");
                    b.ToTable("StudyAttemptSelections");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasGuessed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExplanationViewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("StudySessionId", "AnsweredAtUtc");

                    b.ToTable("StudyAttempts");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("StudyGroups");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanJson")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StartedAtUtc");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AdministrationAuditEvent", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AccountRole", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.RoleDefinition", "RoleDefinition")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RoleDefinition");
                });


            modelBuilder.Entity("LearnPip.Data.Domain.AccountInactivityWarning", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AccountSession", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.EmailLoginCode", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LearnPip.Data.Domain.AccountSession", "InitiatingSession")
                        .WithMany()
                        .HasForeignKey("InitiatingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("InitiatingSession");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RecoveryCredential", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithOne()
                        .HasForeignKey("LearnPip.Data.Domain.RecoveryCredential", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AnswerOption", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExternalIdentity", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupCatalogShare", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.PrivateCatalog", "PrivateCatalog")
                        .WithMany().HasForeignKey("PrivateCatalogId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("SharedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany().HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("PrivateCatalog");
                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupInvitation", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany().HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupMembership", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.RoleDefinition", "RoleDefinition")
                        .WithMany()
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RoleDefinition");

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupVersionShare", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany().HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany().HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.PrivateCatalog", "PrivateCatalog")
                        .WithMany().HasForeignKey("PrivateCatalogId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("StudyGroup");
                    b.Navigation("QuestionVersion");
                    b.Navigation("PrivateCatalog");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupQuestionShare", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("SharedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany()
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.MediaBlob", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.MediaAsset", "MediaAsset")
                        .WithOne()
                        .HasForeignKey("LearnPip.Data.Domain.MediaBlob", "MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.MediaAsset", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany("MediaAssets")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.PrivateCatalog", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.LearningContent", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.FrequentLearningContent", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.LearningContent", "LearningContent")
                        .WithMany().HasForeignKey("LearningContentId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("LearningContent");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionDraft", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithOne("Draft").HasForeignKey("LearnPip.Data.Domain.QuestionDraft", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Question", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Owner")
                        .WithMany("Questions")
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.PrivateCatalog", "PrivateCatalog")
                        .WithMany("Questions").HasForeignKey("PrivateCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("LearnPip.Data.Domain.LearningContent", "LearningContent")
                        .WithMany("Questions").HasForeignKey("LearningContentId")
                        .OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("Owner");
                    b.Navigation("PrivateCatalog");
                    b.Navigation("LearningContent");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExamProfileVersion", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.OfficialCatalogEdition", "CatalogEdition")
                        .WithMany().HasForeignKey("CatalogEditionId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("CatalogEdition");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExamSimulation", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.ExamProfileVersion", "ProfileVersion")
                        .WithMany().HasForeignKey("ProfileVersionId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("ProfileVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AccountExamCredit", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionObjective", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.ExamObjective", "ExamObjective")
                        .WithMany("QuestionObjectives")
                        .HasForeignKey("ExamObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamObjective");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionContentBlock", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany("Blocks").HasForeignKey("QuestionVersionId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LearnPip.Data.Domain.AnswerOption", "AnswerOption")
                        .WithMany("Blocks").HasForeignKey("AnswerOptionId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LearnPip.Data.Domain.MediaAsset", "MediaAsset")
                        .WithMany().HasForeignKey("MediaAssetId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("QuestionVersion");
                    b.Navigation("AnswerOption");
                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.FamilyLink", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null).WithMany()
                        .HasForeignKey("ChildAccountId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null).WithMany()
                        .HasForeignKey("ParentAccountId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LearnPip.Data.Domain.Account", null).WithMany()
                        .HasForeignKey("VerifiedByAccountId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LearnPip.Data.Domain.Account", null).WithMany()
                        .HasForeignKey("RevokedByAccountId").OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LearnPip.Data.Domain.FamilyLinkEvent", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.FamilyLink", null).WithMany()
                        .HasForeignKey("FamilyLinkId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null).WithMany()
                        .HasForeignKey("ActorAccountId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.FamilyGoal", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.FamilyLink", null).WithMany()
                        .HasForeignKey("FamilyLinkId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.PublicSubmission", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany().HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("ReviewedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("GuardianApprovedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.PublicSubmissionPreview", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", null)
                        .WithMany().HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.PublicSubmissionReview", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", null)
                        .WithMany().HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("ModeratorAccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionTranslation", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany().HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.TranslationReport", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionTranslation", "Translation")
                        .WithMany().HasForeignKey("QuestionTranslationId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany().HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Translation");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionVersion", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttemptSelection", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.StudyAttempt", "StudyAttempt")
                        .WithMany("Selections").HasForeignKey("StudyAttemptId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LearnPip.Data.Domain.AnswerOption", "AnswerOption")
                        .WithMany().HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("StudyAttempt");
                    b.Navigation("AnswerOption");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttempt", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.StudySession", "StudySession")
                        .WithMany("Attempts")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyGroup", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudySession", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany("StudySessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Account", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("Questions");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExamObjective", b =>
                {
                    b.Navigation("QuestionObjectives");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.PrivateCatalog", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.LearningContent", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Question", b =>
                {
                    b.Navigation("Draft");
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AnswerOption", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttempt", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionVersion", b =>
                {
                    b.Navigation("Blocks");
                    b.Navigation("AnswerOptions");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RoleDefinition", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudySession", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
