// <auto-generated />
using System;
using LearnPip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnPip.Data.Migrations
{
    [DbContext(typeof(LearnPipDbContext))]
    partial class LearnPipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnPip.Data.Domain.AdministrationAuditEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<Guid?>("ActorAccountId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("NewValue").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("PreviousValue").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("Target").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.HasKey("Id");
                    b.HasIndex("ActorAccountId");
                    b.HasIndex("CreatedAtUtc");
                    b.ToTable("AdministrationAuditEvents");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Key").HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Value").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.HasKey("Key");
                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });


            modelBuilder.Entity("LearnPip.Data.Domain.AccountSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AccountSessions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.EmailLoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InitiatingSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Email", "Purpose", "CreatedAtUtc");

                    b.HasIndex("InitiatingSessionId");

                    b.ToTable("EmailLoginCodes");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RecoveryCredential", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccountId");

                    b.HasIndex("SecretHash")
                        .IsUnique();

                    b.ToTable("RecoveryCredentials");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId", "RoleDefinitionId");

                    b.HasIndex("RoleDefinitionId");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExamObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExamObjectives");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupMembership", b =>
                {
                    b.Property<Guid>("StudyGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("StudyGroupId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleDefinitionId");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupQuestionShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SharedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SharedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SharedByAccountId");

                    b.HasIndex("StudyGroupId", "QuestionId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("GroupQuestionShares");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.MediaBlob", b =>
                {
                    b.Property<Guid>("MediaAssetId").HasColumnType("uuid");
                    b.Property<byte[]>("Data").IsRequired().HasColumnType("bytea");
                    b.HasKey("MediaAssetId");
                    b.ToTable("MediaBlobs");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("OwnerAccountId", "CreatedAtUtc");

                    b.ToTable("MediaAssets", t =>
                        {
                            t.HasCheckConstraint("CK_MediaAssets_ByteLength", "\"ByteLength\" > 0");
                        });
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId", "UpdatedAtUtc");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionObjective", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamObjectiveId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId", "ExamObjectiveId");

                    b.HasIndex("ExamObjectiveId");

                    b.ToTable("QuestionObjectives");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("QuestionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("QuestionVersions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Code")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("StudySessionId", "AnsweredAtUtc");

                    b.ToTable("StudyAttempts");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("StudyGroups");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StartedAtUtc");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AdministrationAuditEvent", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AccountRole", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.RoleDefinition", "RoleDefinition")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RoleDefinition");
                });


            modelBuilder.Entity("LearnPip.Data.Domain.AccountSession", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.EmailLoginCode", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LearnPip.Data.Domain.AccountSession", "InitiatingSession")
                        .WithMany()
                        .HasForeignKey("InitiatingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("InitiatingSession");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RecoveryCredential", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithOne()
                        .HasForeignKey("LearnPip.Data.Domain.RecoveryCredential", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.AnswerOption", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExternalIdentity", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupMembership", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.RoleDefinition", "RoleDefinition")
                        .WithMany()
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RoleDefinition");

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.GroupQuestionShare", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("SharedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.StudyGroup", "StudyGroup")
                        .WithMany()
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.MediaBlob", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.MediaAsset", "MediaAsset")
                        .WithOne()
                        .HasForeignKey("LearnPip.Data.Domain.MediaBlob", "MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.MediaAsset", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany("MediaAssets")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Question", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Owner")
                        .WithMany("Questions")
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionObjective", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.ExamObjective", "ExamObjective")
                        .WithMany("QuestionObjectives")
                        .HasForeignKey("ExamObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamObjective");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionVersion", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyAttempt", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnPip.Data.Domain.StudySession", "StudySession")
                        .WithMany("Attempts")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyGroup", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudySession", b =>
                {
                    b.HasOne("LearnPip.Data.Domain.Account", "Account")
                        .WithMany("StudySessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Account", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("Questions");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.ExamObjective", b =>
                {
                    b.Navigation("QuestionObjectives");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.Question", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.QuestionVersion", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.RoleDefinition", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudyGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("LearnPip.Data.Domain.StudySession", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
